### ISSUE TITLE
Oxymoron in Readme

### ISSUE THREAD

**Issue by Yatekii** [zentoo/zentoo#10]
Zentoo Linux is at the same time more conservative and more **bleeding-edge**. Package updates tend to happen in batches that **are known to work** and are supported by ZenOps Chef.

Please decide to settle for one or the other. They are not logically compatible.

**Comment by TheComet93** [comment]
"[...] _more **conservative** and more **bleeding-edge**_ [...]"

Perhaps this has a deeper, metaphorical meaning. One that cannot be understood by mere mortals such as ourselves. One that can only be understood by ZonOps Chef himself.

**Comment by hollow** [comment]
lol

**Comment by Yatekii** [comment]
Well it's actually "lol" I think. It's your call but you actually contradict yourself twice in that sentence. We just pointed it out. Good luck!

**Comment by nutztherookie** [comment]
sieh an.. wusste nicht, dass die douchcopter jetzt auch github entdeckt haben.  hashtag nix besseres zu tun :tm:

**Comment by TheComet93** [comment]
Man würde erwarten, dass jemand der Software entwickelt auch grammatikalische Logik versteht... Oder versuchst du jetzt echt abzustreiten dass kein logischer Konflikt in diesem Satz vorliegt?

**Comment by hollow** [comment]
please move this discussion elsewhere. the readme explains the oxymoron and it is there intentionally
