### ISSUE TITLE
Readme appears to be outdated

### ISSUE THREAD

**Issue by cstrouse** [zentoo/zentoo#11]
As per the [bugzilla ticket](https://bugs.gentoo.org/show_bug.cgi?id=373219) referenced in the readme the issue preventing wholesale removal of OpenRC in favor of systemd has been marked "fixed/resolved".

Has the work required for the switch been completed yet? If so the repo readme could use a quick update and maybe a link to the relevant commits.

**Comment by hollow** [comment]
this repo is now mostly obsolete, since I have begun to switch all my infrastructure to Ubuntu, now that they finally support systemd. I am not going to maintain any zentoo components after I've finished the migration of my systems and customers.
