### ISSUE TITLE
nginx_upstream_check doesn't work with nginx-1.7.11 ebuild

### ISSUE THREAD

**Issue by jwroblewski** [zentoo/zentoo#9]
[nginx_upstream_check 1.7.2+ patch](https://github.com/zentoo/zentoo/blob/master/www-servers/nginx/files/check_1.7.2%2B.patch) does not apply cleanly to `nginx 1.7.11` sources, which _most likely_ makes the [`epatch` silently fail](https://github.com/zentoo/zentoo/blob/master/www-servers/nginx/nginx-1.7.11.ebuild#L279). The outcome is that the module is not registered with the upstream handlers, and the upstream checks are not triggered.

The problem can be solved by either pulling the [latest version of 1.7.2+ patch](https://github.com/yaoweibin/nginx_upstream_check_module/blob/master/check_1.7.2%2B.patch), or even better -- [upgrading to 1.7.5+ patch](https://github.com/yaoweibin/nginx_upstream_check_module/blob/master/check_1.7.5%2B.patch).

**Comment by hollow** [comment]
current version in zentoo is 1.7.12 and the patch seems to apply just fine:

```
root@bene.dev.zenops.net [130] 09:18:50 /var/tmp/portage/www-servers/nginx-1.7.12/work/nginx-1.7.12
$ patch -p1 < ../nginx_upstream_check_module-0.3.0/check_1.7.2+.patch
patching file src/http/modules/ngx_http_upstream_ip_hash_module.c
patching file src/http/modules/ngx_http_upstream_least_conn_module.c
patching file src/http/ngx_http_upstream_round_robin.c
Hunk #1 succeeded at 9 with fuzz 2.
Hunk #2 succeeded at 95 (offset 4 lines).
Hunk #3 succeeded at 159 (offset 4 lines).
Hunk #4 succeeded at 227 (offset 4 lines).
Hunk #5 succeeded at 339 (offset 4 lines).
Hunk #6 succeeded at 381 (offset 4 lines).
Hunk #7 succeeded at 443 (offset 4 lines).
Hunk #8 succeeded at 541 (offset -1 lines).
patching file src/http/ngx_http_upstream_round_robin.h
```

**Comment by jwroblewski** [comment]
What about the patch file from zentoo repo -- https://github.com/zentoo/zentoo/blob/master/www-servers/nginx/files/check_1.7.2%2B.patch? Isn't it used when producing an ebuild?

    $ pwd
    /tmp/nginx-1.7.12
    $ patch -p1 < ../zentoo/www-servers/nginx/files/check_1.7.2+.patch
    can't find file to patch at input line 11
    Perhaps you used the wrong -p or --strip option?
    The text leading up to this was:
    --------------------------
    |commit 21116e1c0bba730ca59327ffba9320bc63f11462
    |Author: Johan Bergström <bugs@bergstroem.nu>
    |Date:   Thu Jun 19 10:17:22 2014 +1000
    |
    |    Add support for upstream_check to nginx 1.7.2
    |
    |diff --git src/http/modules/ngx_http_upstream_ip_hash_module.c src/http/modules/ngx_http_upstream_ip_hash_module.c
    |index 148d73a..be9e03d 100644
    |--- src/http/modules/ngx_http_upstream_ip_hash_module.c
    |+++ src/http/modules/ngx_http_upstream_ip_hash_module.c
    --------------------------
    File to patch:
